package com.experimentops.avroevent.type;

public enum EventType {
    WORKSPACE_CREATE,
    USER_CREATE,
    USER_INVITE,
    WORKSPACE_CREATION_COMPLETE,
    PASSWORD_RESET,
    PROJECT_CREATE,
    PROJECT_UPDATE,
    PROJECT_STATUS_CHANGE,
    EXPERIMENT_CREATE,
    EXPERIMENT_UPDATE,
    EXPERIMENT_STATUS_CHANGE,
    EXPERIMENT_RUN_REQUESTED,
    DATASET_CREATE,
    DATASET_UPDATE,
    DATASET_STATUS_CHANGE,
    DATASET_VERSION_CREATE,
    DATASET_VERSION_STATUS_CHANGE,
    DATASET_VERSION_SCAN_REQUESTED,
    DATASET_VERSION_SCAN_COMPLETED,
    EXPERIMENT_TYPE_CREATE,
    EXPERIMENT_TYPE_UPDATE,
    EXPERIMENT_TYPE_STATUS_CHANGE
}
