name: experimentops

# All in the same file to make sure they are in same docker network
services:
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: experimentops-kafka
    ports:
      - "9092:9092"
    environment:
      # Single node setup
      KAFKA_NODE_ID: 1
      # before zoo-keeper acted as meta-data coordinator between controller and broker. For this project, its own Kraft is used
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # First is for containers in docker to talk to Kafka. Second is for applications in same container as Kafka to talk. Third is internal Kafka Leader coordinating.
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:9093
      # Controller is not in Advertised Listeners because no external client can ever know about it, only for internal communication
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: experimentops-local-cluster

  # Holds the groups and topics and AVRO schemas of Kafka
  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.1
    container_name: experimentops-schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      # Talks to kafka through the docker network
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081


  platform-api:
    build:
      context: ../../services/applications/platform-api
      dockerfile: Dockerfile
    image: platform-api:local
    container_name: experimentops-platform-api
    depends_on:
      - kafka
      - schema-registry
      - keycloak
      - mailpit
    expose:
      - "8080"
    env_file:
      - .env.local
    environment:
      # aws
      EXPERIMENTOPS_STORAGE_S3_BUCKET: ${EXPERIMENTOPS_S3_BUCKET}
      EXPERIMENTOPS_STORAGE_S3_REGION: ${AWS_REGION}

      #kafka
      kafka.bootstrap-servers: kafka:29092
      kafka.schema.registry-url: http://schema-registry:8081

      # This overrides SpringBoot local address with docker container address
      experimentops.db.host: host.docker.internal
      experimentops.db.port: 55000
      experimentops.db.schema: experimentOps
      experimentops.db.username: experimentops_user
      experimentops.db.password: experimentops_password

      # keycloak
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_MASTER_REALM: master
      KEYCLOAK_MASTER_USERNAME: admin
      KEYCLOAK_MASTER_PASSWORD: admin
      KEYCLOAK_MASTER_CLIENT_ID: admin-cli
      WORKSPACE_CONFIG_SERVER_RSA_KEY: ${WORKSPACE_CONFIG_SERVER_RSA_KEY}

      # mail
      EXPERIMENTOPS_MAIL_HOST: mailpit
      EXPERIMENTOPS_MAIL_PORT: 1025
      EXPERIMENTOPS_MAIL_FROM: no-reply@experimentops.local
      EXPERIMENTOPS_MAIL_AUTH: false
      EXPERIMENTOPS_MAIL_SSL: false
      EXPERIMENTOPS_MAIL_START_TLS: false


  mailpit:
    image: axllent/mailpit:latest
    container_name: experimentops-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  flyway:
    image: flyway/flyway:latest
    container_name: experimentops-flyway
    command:
      -url=jdbc:mysql://host.docker.internal:55000/experimentOps
      -user=experimentops_user
      -password=experimentops_password
      -connectRetries=60
      migrate
    volumes:
      - ../database/migration:/flyway/sql

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: experimentops-keycloak
    command: start-dev
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data

  api-gateway-service:
    build:
      context: ../../services/applications/api-gateway-service
      dockerfile: Dockerfile
    image: api-gateway-service:local
    container_name: experimentops-api-gateway-service
    depends_on:
      - platform-api
      - keycloak
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      services.platform-api.url: http://platform-api:8080
      JWKS_CERTS_FILE: /app/config/experimentops-jwks.json
      JWT_CLIENT_ID: experimentops-web
    volumes:
      - ./jwks/experimentops-jwks.json:/app/config/experimentops-jwks.json:ro

# this persistent volume is to save keycloak all roles and users and realms so even if keycloak image is deleted and re-built then we dont loose our data.
# Since we have not mentioned the path where data is saved. This is internally managed by keycloak
volumes:
  keycloak_data:
