<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.3</version>
    <relativePath/>
  </parent>


  <groupId>com.experimentops</groupId>
  <artifactId>root</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>

  <properties>
    <revision>0.1.0</revision>
    <avro.version>1.12.0</avro.version>
    <awaitility.version>3.0.0</awaitility.version>
    <confluent.version>5.3.0</confluent.version>
    <jspecify.version>1.0.0</jspecify.version>
    <jakarta.annotation-api.version>3.0.0</jakarta.annotation-api.version>
    <jackson-databind-nullable.version>0.2.6</jackson-databind-nullable.version>
    <jjwt.version>0.12.6</jjwt.version>
    <lombok.version>1.18.38</lombok.version>
    <keycloak-admin-client.version>15.0.2</keycloak-admin-client.version>
    <keycloak-adapter-bom.version>9.0.2</keycloak-adapter-bom.version>
    <resteasy-multipart-provider.version>6.2.11.Final</resteasy-multipart-provider.version>
    <commons-io.version>2.19.0</commons-io.version>
    <openapi.maven.generator.version>7.17.0</openapi.maven.generator.version>
    <spring-cloud.version>2025.0.0</spring-cloud.version>
    <swagger-annotations-jakarta.version>2.2.21</swagger-annotations-jakarta.version>
    <flatten.maven-plugin.version>1.6.0</flatten.maven-plugin.version>
    <java.version>21</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <apache.commons.lang3.version>3.18.0</apache.commons.lang3.version>
  </properties>

  <modules>
    <module>libs</module>
    <module>applications</module>
  </modules>

  <dependencies>
    <dependency>
      <groupId>org.jspecify</groupId>
      <artifactId>jspecify</artifactId>
      <version>${jspecify.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>${flatten.maven-plugin.version}</version>
        <configuration>
          <flattenMode>resolveCiFriendliesOnly</flattenMode>
          <updatePomFile>true</updatePomFile>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
          <execution>
            <id>flatten.clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
