{
  "namespace": "com.experimentops.dataset.version.scan.event",
  "type": "record",
  "name": "DatasetVersionScanCompletedEvent",
  "fields": [
    { "name": "metadata", "type": "com.experimentops.common.kafka.model.event.ExperimentOpsMetadataEvent" },
    {
      "name": "payload",
      "type": [ "null",
        {
          "type": "record",
          "name": "DatasetVersionScanCompletedEventPayload",
          "fields": [
            { "name": "message", "type": ["null", "string"], "default": null, "avro.java.string": "String" },
            { "name": "previewUri", "type": ["null", "string"], "default": null, "avro.java.string": "String" }
          ]
        }
      ],
      "default": null
    }
  ]
}
