{
  "namespace": "com.experimentops.dataset.version.event",
  "type": "record",
  "name": "DatasetVersionMutationEvent",
  "fields": [
    { "name": "metadata", "type": "com.experimentops.common.kafka.model.event.ExperimentOpsMetadataEvent" },
    {
      "name": "payload",
      "type": [ "null",
        {
          "type": "record",
          "name": "DatasetVersionMutationEventPayload",
          "fields": [
            { "name": "datasetUuid", "type": ["null", "string"], "default": null, "avro.java.string": "String" },
            { "name": "fileName",    "type": ["null", "string"], "default": null, "avro.java.string": "String" },
            { "name": "storageUri",  "type": ["null", "string"], "default": null, "avro.java.string": "String" },
            { "name": "format",      "type": ["null", "string"], "default": null, "avro.java.string": "String" },
            { "name": "size",        "type": ["null", "long"], "default": null },
            { "name": "status",      "type": ["null", "string"], "default": null, "avro.java.string": "String" },
            { "name": "failureMessage", "type": ["null", "string"], "default": null, "avro.java.string": "String" }
          ]
        }
      ],
      "default": null
    }
  ]
}
