{
  "namespace": "com.experimentops.experiment.type.event",
  "type": "record",
  "name": "ExperimentTypeMutationEvent",
  "fields": [
    { "name": "metadata", "type": "com.experimentops.common.kafka.model.event.ExperimentOpsMetadataEvent" },
    {
      "name": "payload",
      "type": [ "null",
        {
          "type": "record",
          "name": "ExperimentTypeMutationEventPayload",
          "fields": [
            { "name": "name", "type": ["null", "string"], "default": null, "avro.java.string": "String" },
            { "name": "defaultConfig", "type": ["null", "string"], "default": null, "avro.java.string": "String" },
            { "name": "formatMappings", "type": ["null", "string"], "default": null, "avro.java.string": "String" },
            { "name": "timeWeight", "type": ["null", "int"], "default": null },
            { "name": "status", "type": ["null", "string"], "default": null, "avro.java.string": "String" }
          ]
        }
      ],
      "default": null
    }
  ]
}
