{
  "namespace": "com.experimentops.user.event",
  "type": "record",
  "name": "UserMutationEvent",
  "fields": [
    { "name": "metadata", "type": "com.experimentops.common.kafka.model.event.ExperimentOpsMetadataEvent" },
    {
      "name": "payload",
      "type": {
        "type": "record",
        "name": "UserMutationEventPayload",
        "fields": [
          { "name":  "workspaceCreation", "type": "boolean", "default": false},
          { "name": "userEmail",      "type": ["null", "string"], "default": null, "avro.java.string": "String" },
          { "name": "userPassword",   "type": ["null", "string"], "default": null, "avro.java.string": "String" },
          { "name": "userFirstName",  "type": ["null", "string"], "default": null, "avro.java.string": "String" },
          { "name": "userLastName",   "type": ["null", "string"], "default": null, "avro.java.string": "String" },
          { "name": "userRole",   "type": ["null", "string"], "default": null, "avro.java.string": "String" }
        ]
      }
    }
  ]
}