package com.experimentops.gateway.util;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.nio.file.Files;
import java.nio.file.Path;

// Provides keys to verify tokens generated by Keycloak
@Component
public class JwtCertLoader {

    private static final Logger log = LoggerFactory.getLogger(JwtCertLoader.class);

    @Value("${jwks.certs:}")
    private String jwksCerts;

    @Value("${jwks.certs-file:}")
    private String jwksCertsFile;

    public String loadCerts() {
        log.info("Loading JWKS certs. Inline certs present: {}, cert file path present: {}",
                StringUtils.isNotBlank(jwksCerts),
                StringUtils.isNotBlank(jwksCertsFile));

        if (StringUtils.isNotBlank(jwksCerts)) {
            return jwksCerts;
        }

        if (StringUtils.isBlank(jwksCertsFile)) {
            return null;
        }

        try {
            return Files.readString(Path.of(jwksCertsFile));
        } catch (Exception ex) {
            log.warn("Unable to read JWKS certs from file: {}", jwksCertsFile, ex);
            return null;
        }
    }
}