package com.experimentops.gateway.util;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;


// Provides keys to check the token is generated by whom from keycloak
@Component
public class JwtCertLoader {
    @Value("${jwks.certs}") private String jwksCerts;

    public String loadCerts() {
        return jwksCerts;
    }
}
