package com.experimentops.gateway.util;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;

import java.time.Duration;

// Provides keys to check the token is generated by whom from keycloak
@Component
public class JwtCertLoader {
    @Value("${jwks.certs}") private String jwksCerts;

    public String loadCerts() {
        return jwksCerts;
    }
}
