name: API Gateway Service

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [latest]
    paths:
      - services/pom.xml
      - services/libs/**
      - services/applications/pom.xml
      - services/applications/api-gateway-service/**
      - .github/workflows/java-service-test.yml
      - .github/workflows/java-service-build.yml
      - .github/workflows/api-gateway-service.yml

permissions:
  contents: read
  packages: write

jobs:
  test:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    uses: ./.github/workflows/java-service-test.yml
    with:
      service-path: applications/api-gateway-service
  build-and-push:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    uses: ./.github/workflows/java-service-build.yml
    with:
      service-name: api-gateway-service
      service-path: applications/api-gateway-service
