{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: experimentops
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "experimentops.labels" . | nindent 4 }}
  {{- if .Values.ingress.tls.enabled }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.frontendHost }}
        - {{ .Values.ingress.apiHost }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.frontendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: frontend, port: { number: 80 } } }
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend: { service: { name: api-gateway-service, port: { number: 8080 } } }
{{- end }}
