{{- range $secret := .Values.sealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    {{- toYaml $secret.encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ $secret.name }}
      namespace: {{ $.Release.Namespace }}
    type: {{ default "Opaque" $secret.type }}
---
{{- end }}
